version: '3.4'

services:
  prometheus:
    image: prometheus
    build:
      context: .
      dockerfile: prometheus/Dockerfile
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
